DEFAULT_REPEAT_INTERVAL_MINUTES = 5

DEFAULT_TIMEZONE = "Europe/Minsk"

DRAFT_EXPIRATION_HOURS = 12

SCHEDULER_POLL_INTERVAL_SECONDS = 10

VOICE_MAX_FILE_SIZE_MB = 20

VOICE_MAX_DURATION_SECONDS = 15

VOICE_TRANSCRIPTION_COMPUTE_TYPE = "int8"

VOICE_TRANSCRIPTION_DEVICE = "cpu"

VOICE_TRANSCRIPTION_LANGUAGE = "ru"

VOICE_TRANSCRIPTION_MODEL = "base"
